### ISSUE TITLE
irit-stac evaluate : TypeError

### ISSUE THREAD

**Issue by eipiplusun** [irit-melodi/irit-stac#23]
When running "irit-stac evaluate", the process ends on a TypeError message:

  File "/home/antoine/Documents/melodi/irit-stac/stac/harness/turn_constraint.py", line 83, in fit
    self._learner.fit(dpacks, targets, nonfixed_pairs=nonfixed_pairs)
TypeError: fit() got an unexpected keyword argument 'nonfixed_pairs'

**Comment by moreymat** [comment]
irit-stac is ahead on attelo/master. This should resolve when I merge the current development branch of attelo into master, hopefully tomorrow.

**Comment by moreymat** [comment]
Closed by irit-melodi/educe#87, irit-melodi/attelo#56, irit-melodi/irit-stac#24.
